<div class="row">
    <div class="span12">
        <h3>Comparing <?= $className; ?> with identifiers of <?= $id ?> between revisions <?= $oldRev ?> and <?= $newRev ?> </h3>
        <table  class="table table-striped table-condensed table-hover table-bordered ">
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Deleted</th>
                    <th>Same</th>
                    <th>Updated</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($diff as $field => $value): ?>
                    <tr>
                        <td><?= $field ?></td>
                        <td> 
                            <?php if ($value["old"] instanceof \DateTime): ?>
                                <?php echo $value["old"]->format("r"); ?>
                            <?php else: ?>
                                <?php echo $value["old"]; ?>    
                            <?php endif; ?></td>
                        <td>
                            <?php if ($value["same"] instanceof \DateTime): ?>
                                <?php echo $value["same"]->format("r"); ?>
                            <?php else: ?>
                                <?php echo $value["same"]; ?>    
                            <?php endif; ?>
                        </td>
                        <td> 
                            <?php if ($value["new"] instanceof \DateTime): ?>
                                <?php echo $value["new"]->format("r"); ?>
                            <?php else: ?>
                                <?php echo $value["new"]; ?>    
                            <?php endif; ?></td>
                    </tr>
                <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>