<h1>Comparing <?= $className; ?> with identifiers of
    <?= $id ?> between revisions <?= $oldRev ?> and <?= $newRev ?> </h1>
<div class="row">
    <div class="span12">
        <table  class="table table-striped table-hover table-bordered ">
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Deleted</th>
                    <th>Same</th>
                    <th>Updated</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($diff as $field => $value): ?>
                    <tr>
                        <td><?= $field ?></td>
                        <td>
                            <?php if ($value["old"] instanceof \DateTime): ?>
                                <?= $this->DateTimeFormatter($value["old"]); ?>
                            <?php else: ?>
                                <?php echo $value["old"]; ?>
                            <?php endif; ?></td>
                        <td>
                            <?php if ($value["same"] instanceof \DateTime): ?>
                                <?= $this->DateTimeFormatter($value["same"]); ?>
                            <?php else: ?>
                                <?php echo $value["same"]; ?>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if ($value["new"] instanceof \DateTime): ?>
                                <?= $this->DateTimeFormatter($value["new"]); ?>
                            <?php else: ?>
                                <?php echo $value["new"]; ?>
                            <?php endif; ?></td>
                    </tr>
                <? endforeach; ?>
            </tbody>
        </table>
    </div>
</div>