<h1>Audit</h1>

<table class="table table-striped table-hover table-bordered">
    <caption>
        All Revisons for
            <a href="<?=

                    $this->url(
                        'audit/entity',
                        array(
                            'entityClass' => $this->entityClass,
                        )
                    );?>
        " class="btn btn-primary"><?= $this->escapeHtml($this->entityClass); ?></a>
    </caption>
    <thead>
        <tr>
            <th>Revision</th>
            <th>Timestamp</th>
            <th>Audit Revision Entity</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tbody>

<?php
foreach ($this->revisionEntities as $revisionEntity) {
?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $revisionEntity->getRevision()->getId(); ?>

                </a>
            </td>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revisionEntity->getRevision()->getId()
                        )
                    );
                ?>"><?= $this->AuditDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?></a>
            </td>
            <td>
                <a class="btn btn-<?php
                    switch ($revisionEntity->getRevision()->getRevisionType()) {
                        case 'INS':
                            echo 'success';
                            break;
                        case 'UPD':
                            echo 'warning';
                            break;
                        case 'DEL':
                            echo 'danger';
                            break;
                        default:
                            echo 'info';
                    }
                ?>"
                    href="<?=
                        $this->url(
                            'audit/revision-entity',
                            array(
                                'revisionEntityId' => $revisionEntity->getId(),
                            )
                        );?>">

                            (<?= $revisionEntity->getId(); ?>)
                            <?= $this->escapeHtml($revisionEntity->getAuditEntity()->getAuditedEntityClass()); ?>
                            <div class="entityKeys">
                                <?php
                                $rows = array();
                                foreach($revisionEntity->getEntityKeys() as $key => $value) {
                                    $rows[] = $this->escapeHtml($key) . ' => ' . $this->escapeHtml($value);
                                }
                                echo implode(', ', $rows);
                                ?>
                            </div>
                    </a>

            </td>

            <td><?= $this->escapeHtml($revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <a href="#" class="btn btn-default">
                    <?php
                        if ($revisionEntity->getRevision()->getUser()) {
                            echo $this->gravatar($revisionEntity->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->zfcUserDisplayName($revisionEntity->getRevision()->getUser());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
<?php
}
?>

    </tbody>
</table>

