<h1>Audit All Entity Revisions</h1>

<?php $paginator = $this->auditEntityPaginator($page, $this->entityClass); ?>

<table class="table table-striped table-hover table-bordered">
    <caption>
        All Revison Entities for
            <a href="<?=

                    $this->url(
                        'audit/entity',
                        array(
                            'entityClass' => $this->entityClass,
                        )
                    );?>
        " class="btn btn-primary"><?= $this->escapeHtml($this->entityClass); ?></a>
    </caption>
    <thead>
        <tr>
            <th colspan="4">
                <?= $this->paginationControl($paginator,
                'Sliding',
                'zf2-entity-audit/pagination/entity',
                    array(
                        'route' => 'audit/entity',
                        'entityClass' => $this->entityClass,
                    )); ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th colspan="4">
                <?= $this->paginationControl($paginator,
                'Sliding',
                'zf2-entity-audit/pagination/entity',
                    array(
                        'route' => 'audit/entity',
                        'entityClass' => $this->entityClass,
                    )); ?>
            </th>
        </tr>
    </tfoot>

    <tbody>

<?php
foreach ($paginator as $revisionEntity) {
?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $revisionEntity->getRevision()->getId(); ?>
                    @ <?= $this->AuditDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?></a>
            </td>
            <td>
                <a class="btn btn-<?php
                    switch ($revisionEntity->getRevisionType()) {
                        case 'INS':
                            echo 'success';
                            break;
                        case 'UPD':
                            echo 'warning';
                            break;
                        case 'DEL':
                            echo 'danger';
                            break;
                        default:
                            echo 'info';
                    }
                ?>"
                    href="<?=
                        $this->url(
                            'audit/revision-entity',
                            array(
                                'revisionEntityId' => $revisionEntity->getId(),
                            )
                        );?>">

                            (<?= $revisionEntity->getId(); ?>)
                            <?= $this->escapeHtml($revisionEntity->getAuditEntity()->getAuditedEntityClass()); ?>
                            <div class="entityKeys">
                                <?php
                                $rows = array();
                                foreach($revisionEntity->getEntityKeys() as $key => $value) {
                                    $rows[] = $this->escapeHtml($key) . ' => ' . $this->escapeHtml($value);
                                }
                                echo implode(', ', $rows);
                                ?>
                            </div>
                    </a>

            </td>

            <td><?= $this->escapeHtml($revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($revisionEntity->getRevision()->getUser()) {
                        echo $this->url('audit/user', array('userId' => $revisionEntity->getRevision()->getUser()->getId()));
                    } else {
                        echo $this->url('audit/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($revisionEntity->getRevision()->getUser()) {
                            echo $this->gravatar($revisionEntity->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->zfcUserDisplayName($revisionEntity->getRevision()->getUser());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
<?php
}
?>

    </tbody>
</table>

