<h1>Audit Entity History</h1>

<table class="table table-striped table-hover table-bordered">
    <caption>
        <?= $this->escapeHtml($this->entityClass); ?>
    </caption>
    <thead>
        <tr>
            <th>Revision</th>
            <th>Audit Revision</th>
            <th>Timestamp</th>
            <th>Entity</th>
            <th>Key Fields</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tbody>

<?php
foreach ($this->revisionEntities as $revisionEntity) {
?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $revisionEntity->getRevision()->getId(); ?>

                </a>
            </td>
            <td><?= $revisionEntity->getId(); ?></td>
            <td><?php echo $this->AuditDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?></td>
            <td>
                <a class="btn btn-<?php
                    switch ($revisionEntity->getRevision()->getRevisionType()) {
                        case 'INS':
                            echo 'success';
                            break;
                        case 'UPD':
                            echo 'warning';
                            break;
                        case 'DEL':
                            echo 'danger';
                            break;
                        default:
                            echo 'info';
                    }
                ?>"
                    href="<?=
                        $this->url(
                            'audit/revision-entity',
                            array(
                                'revisionEntityId' => $revisionEntity->getId(),
                            )
                        );?>"
                    >

                        <?= $this->escapeHtml($revisionEntity->getAuditEntity()->getAuditedEntityClass()); ?>
                    </a>

            </td>

            <td><?= var_dump($revisionEntity->getEntityKeys()); ?></td>
            <td><?= $this->escapeHtml($revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <a href="#" class="btn btn-default">
                    <?php
                        if ($revisionEntity->getRevision()->getUser()) {
                            echo $this->gravatar($revisionEntity->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($revisionEntity->getRevision()->getUser()->getEmail());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
<?php
}
?>

    </tbody>
</table>

