<div class="row">
    <div class="span6">
        <h1>Revisions</h1>
        <table class="table table-striped table-condensed table-hover table-bordered ">
            <thead>
                <tr>
                    <td>Revision Id</td>
                    <td>Time of Action</td>
                    <td>Username</td>

                </tr>
            </thead>
            <tbody>
                <?php foreach ($revisions as $r): ?>
                    <tr>
                        <td><?= $r->getRev(); ?></td>
                        <td><span class="label label-info"><?= $r->getTimestamp()->format("Y-m-d H:i:s"); ?></span></td>
                        <td><?= $r->getUsername(); ?></td>

                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="span6">

    </div>
</div>