<span class="pull-right">
    <a href="#" class="btn btn-success">Insert</a>
    <a href="#" class="btn btn-warning">Update</a>
    <a href="#" class="btn btn-danger">Delete</a>
</span>

<h1>Audit</h1>

<?php $paginator = $this->auditRevisionPaginator($this->page); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'zf2-entity-audit/pagination/revision', array('route' => 'audit/page'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'zf2-entity-audit/pagination/revision', array('route' => 'audit/page'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $revision) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revision->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revision->getId());?>
                    @ <?php echo $this->AuditDateTimeFormatter($revision->getTimestamp()); ?>

                </a>
            </td>

            <td>
            <?php
            foreach ($revision->getRevisionEntities() as $revisionEntity) {
            ?>
            <div>

                <a class="btn btn-<?php
                    switch ($revisionEntity->getRevisionType()) {
                        case 'INS':
                            echo 'success';
                            break;
                        case 'UPD':
                            echo 'warning';
                            break;
                        case 'DEL':
                            echo 'danger';
                            break;
                        default:
                            echo 'info';
                    }
                ?>"
                    href="<?=
                        $this->url(
                            'audit/revision-entity',
                            array(
                                'revisionEntityId' => $revisionEntity->getId(),
                            )
                        );?>"
                    >
                        (<?= $revisionEntity->getId(); ?>)
                        <?= $this->escapeHtml($revisionEntity->getAuditEntity()->getAuditedEntityClass()); ?>
                        <div class="entityKeys">
                            <?php
                            $rows = array();
                            foreach($revisionEntity->getEntityKeys() as $key => $value) {
                                $rows[] = $this->escapeHtml($key) . ' => ' . $this->escapeHtml($value);
                            }
                            echo implode(', ', $rows);
                            ?>
                        </div>
                    </a>

                    <?php
                    if ($options = $this->auditOptions($revisionEntity->getTargetEntityClass())) {
                        $routeOptions = array_merge($options['defaults'], $revisionEntity->getEntityKeys());
                    ?>
                        <a class="btn btn-info" href="<?=
                            $this->url($options['route'], $routeOptions);
                        ?>">Data</a>
                    <?php
                    }
                    ?>

                </div>
            <?php
            }
            ?>
            </td>

            <td><?= $this->escapeHtml($revision->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($revision->getUser()) {
                        echo $this->url('audit/user', array('userId' => $revision->getUser()->getId()));
                    } else {
                        echo $this->url('audit/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($revision->getUser()) {
                            echo $this->gravatar($revision->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->zfcUserDisplayName($revision->getUser());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
