<h1>Audit Revision Entity</h1>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $this->revisionEntity->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->revisionEntity->getRevision()->getId(); ?>

                    @ <?php echo $this->AuditDateTimeFormatter($revisionEntity->getRevision()->getTimestamp()); ?>
                </a>

            </td>
            <td>

                <a class="btn btn-<?php
                    switch ($revisionEntity->getRevisionType()) {
                        case 'INS':
                            echo 'success';
                            break;
                        case 'UPD':
                            echo 'warning';
                            break;
                        case 'DEL':
                            echo 'danger';
                            break;
                        default:
                            echo 'info';
                    }
                ?>"
                    href="<?=
                        $this->url(
                            'audit/revision-entity',
                            array(
                                'revisionEntityId' => $this->revisionEntity->getId(),
                            )
                        );?>"
                    >

                        (<?= $this->revisionEntity->getId(); ?>)

                        <?= $this->escapeHtml($this->revisionEntity->getAuditEntity()->getAuditedEntityClass()); ?>
                        <div class="entityKeys">
                            <?php
                            $rows = array();
                            foreach($revisionEntity->getEntityKeys() as $key => $value) {
                                $rows[] = $this->escapeHtml($key) . ' => ' . $this->escapeHtml($value);
                            }
                            echo implode(', ', $rows);
                            ?>
                        </div>
                    </a>

                    <?php
                    if ($options = $this->auditOptions($revisionEntity->getTargetEntityClass())) {
                        $routeOptions = array_merge($options['defaults'], $revisionEntity->getEntityKeys());
                    ?>
                        <a class="btn btn-info" href="<?=
                            $this->url($options['route'], $routeOptions);
                        ?>">Data</a>
                    <?php
                    }
                    ?>
            </td>

            <td><?= $this->escapeHtml($this->revisionEntity->getRevision()->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($this->revisionEntity->getRevision()->getUser()) {
                        echo $this->url('audit/user', array('userId' => $this->revisionEntity->getRevision()->getUser()->getId()));
                    } else {
                        echo $this->url('audit/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($this->revisionEntity->getRevision()->getUser()) {
                            echo $this->gravatar($this->revisionEntity->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->zfcUserDisplayName($this->revisionEntity->getRevision()->getUser());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
    </tbody>
</table>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        Audited Entity Values
    </caption>
    <thead>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->auditService()->getEntityValues($this->revisionEntity->getAuditEntity()) as $field => $value) { ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                    <?php if ($value instanceof \DateTime): ?>
                        <?php echo  $this->AuditDateTimeFormatter($value); ?>
                    <?php else : ?>
                        <?php  echo $this->escapeHtml($value); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php
            }
        ?>
    </tbody>
</table>


<form action="<?=
    $this->url('audit/compare',
        array(
        )
    );
    ?>" method="post">

<?php
    $first = true;
    $oldSet = false;
    $paginator = $this->auditRevisionEntityPaginator($page, $this->revisionEntity->getAuditEntity());
?>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        Compare Revision Entities
    </caption>
    <thead>
        <tr>
            <th colspan="6">
                <?=
                $this->paginationControl($paginator,
                    'Sliding',
                    'zf2-entity-audit/pagination/revision-entity',
                    array(
                        'route' => 'audit/revision-entity',
                        'revisionEntityId' => $this->revisionEntity->getId(),
                    )
                ); ?>
            </th>

        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
            <th>Old</th>
            <th>New</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th colspan="6">
                <?=
                $this->paginationControl($paginator,
                    'Sliding',
                    'zf2-entity-audit/pagination/revision-entity',
                    array(
                        'route' => 'audit/revision-entity',
                        'revisionEntityId' => $this->revisionEntity->getId(),
                    )
                ); ?>
            </th>

        </tr>
    </tfoot>
    <tbody>
        <?php
        foreach ($paginator as $rev) {
        ?>
            <tr>
                <td>
                    <a href="<?=
                        $this->url('audit/revisions',
                            array(
                                'revisionId' => $rev->getRevision()->getId()
                            )
                        );
                    ?>">

                        <?= $rev->getRevision()->getId(); ?>
                        @ <?php echo $this->AuditDateTimeFormatter($rev->getRevision()->getTimestamp()); ?>

                    </a>
                </td>

                <td>
                    <a href="<?=
                        $this->url('audit/revision-entity',
                            array(
                                'revisionEntityId' => $rev->getId()
                            )
                        );
                    ?>" class="btn btn-<?php
                    switch ($rev->getRevisionType()) {
                        case 'INS':
                            echo 'success';
                            break;
                        case 'UPD':
                            echo 'warning';
                            break;
                        case 'DEL':
                            echo 'danger';
                            break;
                        default:
                            echo 'info';
                    }
                ?>">
                        (<?= $rev->getId(); ?>)

                        <?= $this->escapeHtml($this->revisionEntity->getAuditEntity()->getAuditedEntityClass()); ?>
                        <div class="entityKeys">
                            <?php
                            $rows = array();
                            foreach($revisionEntity->getEntityKeys() as $key => $value) {
                                $rows[] = $this->escapeHtml($key) . ' => ' . $this->escapeHtml($value);
                            }
                            echo implode(', ', $rows);
                            ?>
                        </div>

                    </a>
                </td>

                <td><?= $this->escapeHtml($rev->getRevision()->getComment()); ?></td>

                <td>
                    <a href="<?php
                        if ($rev->getRevision()->getUser()) {
                            echo $this->url('audit/user', array('userId' => $rev->getRevision()->getUser()->getId()));
                        } else {
                            echo $this->url('audit/user', array('userId' => '0'));
                        }
                    ?>" class="btn btn-default">
                        <?php
                            if ($rev->getRevision()->getUser()) {
                                echo $this->gravatar($rev->getRevision()->getUser()->getEmail(), array('img_size' => 24));
                                echo ' ';
                                echo $this->zfcUserDisplayName($rev->getRevision()->getUser());
                            } else {
                                echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                                echo ' Anonymous';
                            }
                        ?>
                    </a>
                </td>

                <td>
                    <input type="radio" name="revisionEntityId_old" value="<?php  echo $this->escapeHtml($rev->getId()); ?>"
                        <?php
                        if (sizeof($paginator) == 1 or ($rev == $this->revisionEntity and !$first) or (!$oldSet and !$first)) {
                            echo 'checked="checked"';
                            $oldSet = true;
                        }
                        ?> />
                </td>
                <td>
                    <input type="radio" name="revisionEntityId_new" value="<?php  echo $this->escapeHtml($rev->getId()); ?>"
                        <?php
                        if ($first) {
                            echo 'checked="checked"';
                            $first = false;
                        }
                        ?> />
                </td>
            </tr>
            <?php
            }
            ?>
    </tbody>
</table>

    <input type="submit" class="btn btn-primary" value="Compare revisions" />

</form>

    <a href="<?=
            $this->url(
                'audit/entity',
                array(
                    'entityClass' => $this->revisionEntity->getAuditEntity()->getAuditedEntityClass(),
                )
            );?>
    " class="btn btn-primary">All Revisons for <?= $this->escapeHtml($this->revisionEntity->getAuditEntity()->getAuditedEntityClass()); ?></a>
