<h1>Audit Revision</h1>

<table class="table table-striped table-hover table-bordered">
    <caption>
        Revision
    </caption>
    <thead>
        <tr>
            <th>Revision</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                <?= $this->escapeHtml($this->revision->getId());?>

                @ <?php echo $this->AuditDateTimeFormatter($this->revision->getTimestamp()); ?>
            </td>

            <td><?= $this->escapeHtml($this->revision->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($this->revision->getUser()) {
                        echo $this->url('audit/user', array('userId' => $this->revision->getUser()->getId()));
                    } else {
                        echo $this->url('audit/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($this->revision->getUser()) {
                            echo $this->gravatar($this->revision->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->zfcUserDisplayName($this->revision->getUser());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
    </tbody>
</table>


<?php
foreach ($this->revision->getRevisionEntities() as $revisionEntity) {
?>

<a class="btn btn-<?php
    switch ($revisionEntity->getRevisionType()) {
        case 'INS':
            echo 'success';
            break;
        case 'UPD':
            echo 'warning';
            break;
        case 'DEL':
            echo 'danger';
            break;
        default:
            echo 'info';
    }
?>"
    href="<?=
        $this->url(
            'audit/revision-entity',
            array(
                'revisionEntityId' => $revisionEntity->getId(),
            )
        );?>"
    >
        (<?= $revisionEntity->getId(); ?>)
        <?= $this->escapeHtml($revisionEntity->getAuditEntity()->getAuditedEntityClass()); ?>
        <div class="entityKeys">
            <?php
            $rows = array();
            foreach($revisionEntity->getEntityKeys() as $key => $value) {
                $rows[] = $this->escapeHtml($key) . ' => ' . $this->escapeHtml($value);
            }
            echo implode(', ', $rows);
            ?>
        </div>
    </a>

    <?php
    if ($options = $this->auditOptions($revisionEntity->getTargetEntityClass())) {
        $routeOptions = array_merge($options['defaults'], $revisionEntity->getEntityKeys());
    ?>
        <a class="btn btn-info" href="<?=
            $this->url($options['route'], $routeOptions);
        ?>">Data</a>
    <?php
    }
    ?>


<table class="table table-striped table-hover table-bordered ">
    <thead>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->auditService()->getEntityValues($revisionEntity->getAuditEntity()) as $field => $value): ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                    <?php if ($value instanceof \DateTime): ?>
                        <?php echo  $this->AuditDateTimeFormatter($value); ?>
                    <?php else : ?>
                        <?php  echo $this->escapeHtml($value); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<?php
}
