<div class="row">
    <div class="span12">
        <h3>Detail of <?= $className; ?>  with identifiers of <?= $id; ?> at revisions <?= $rev; ?></h3>

        <p><a href="<?php echo $this->url("audit_viewentity",array("id" => $id , "className" => $className));?>">Compare revisions</a></p>
        <table class="table table-striped table-condensed table-hover table-bordered ">
            <thead><tr>
                    <th>Field</th>
                    <th>Value</th>
                </tr></thead>
            <tbody>
                <?php foreach ($data as $field => $value): ?>
                    <tr>
                        <td><?= $field; ?></td>
                        <td>
                            <?php if ($value instanceof \DateTime): ?>
                                <?= $value->format("r"); ?>
                            <?php else : ?>
                                <?= $value; ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>