<h1>Audit log for <?php  echo $this->escapeHtml($className); ?> identifier <?php  echo $this->escapeHtml($id); ?></h1>

<form action="<?=
    $this->url('audit_compare',
        array(
            'id' => $id ,
            'className' => $className
        )
    );
    ?>" method="post">

<div class="row">
    <div class="span12">
        <table class="table table-striped table-hover table-bordered">

            <thead>
                <tr>
                    <th colspan="3">&nbsp;</th>
                    <th colspan="2">Compare</th>
                </tr>
                <tr>
                    <th>Revision</th>
                    <th>Timestamp</th>
                    <th>User</th>
                    <th>Old</th>
                    <th>New</th>
                </tr>
            </thead>

            <tbody>
                <?php
                $i = 0;
                foreach ($revisions  as $revision) {
                ?>

                <tr>
                    <td>
                        <a href="<?=
                            $this->url('audit_viewdetails',
                            array(
                                'id' => $id ,
                                'className' => $className,
                                'rev' =>$revision->getRev()
                            )
                        ); ?>">
                            <?php  echo $this->escapeHtml($revision->getRev()); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?=
                            $this->url('audit_viewdetails',
                            array(
                                'id' => $id ,
                                'className' => $className,
                                'rev' =>$revision->getRev()
                            )
                        ); ?>">
                            <?php echo  $this->DateTimeFormatter($revision->getTimestamp()); ?>
                        </a>
                    </td>
                    <td>
                        <span class="label label-info">
                            <?php echo  ($revision->getUsername()) ?: 'Anonymous'; ?>
                        </span>
                    </td>

                    <td>
                        <input type="radio" name="oldRev" value="<?php  echo $this->escapeHtml($revision->getRev()); ?>"
                            <?php echo  (sizeof($revisions) == 1 or $i == 1) ? 'checked="checked"': ''; ?> />
                    </td>
                    <td>
                        <input type="radio" name="newRev" value="<?php  echo $this->escapeHtml($revision->getRev()); ?>"
                            <?php echo  (!$this->escapeHtml($i)) ? 'checked="checked"': ''; ?> />
                    </td>
                </tr>
                <?php
                    $i++;
                }
                ?>

            </tbody>

        </table>
    </div>
</div>

<div class="row">
    <div class="span12">
        <input type="submit" class="btn btn-primary" value="Compare revisions" />
    </div>
</div>

</form>
