<h1>Audit entry <?= $className; ?> identifier <?= $id; ?> at revision <?= $rev; ?></h1>

<div class="row">
    <div class="span12">
        <table class="table table-striped table-hover table-bordered ">
            <thead><tr>
                    <th>Field</th>
                    <th>Value</th>
                </tr></thead>
            <tbody>
                <?php foreach ($data as $field => $value): ?>
                    <tr>
                        <td><?= $field; ?></td>
                        <td>
                            <?php if ($value instanceof \DateTime): ?>
                                <?= $value->format("r"); ?>
                            <?php else : ?>
                                <?= $value; ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<a class="btn btn-link" href="<?=
    $this->url('audit_viewentity',
        array(
            'id' => $id,
            'className' => $className
        )
    );?>">
   View revisions
</a>
