<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 EntityAudit '); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')
        ?>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('application') ?>"> <i class="icon-list"></i> ZF2EntityAudit</a>
                    <div class="nav-collapse">
                        <ul class="nav pull-right">
                            <?php
                            if ($this->zfcUserIdentity()) {
                            ?>
                            <li id="user-menu" class="dropdown">
                                <a id="user-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 24)); ?>
                                    <?php echo $this->zfcUserDisplayName() ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="user-drop" role="menu">
                                    <li role="menuitem"><a href="/user/logout">Logout</a></li>
                                </ul>
                            </li>
                        <?php
                        } else {
                        ?>
                            <li><a href="/user/login">Login</a></li>
                        <?php
                        }
                        ?>
                        </ul>

                        <ul class="nav">
                            <li><a href="<?php echo $this->url('application') ?>"><i class="icon-home"></i> Home</a></li>
                            <li><a href="<?php echo $this->url('audit_index') ?>"><i class="icon-edit"></i> Audit Revisions</a></li>
                            <li><a href="https://github.com/tawfekov/ZF2EntityAudit"><i class="icon-book"></i> Source Code</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <div class="container">
            <div>
                <hr/>
                <footer>
                    <p>&copy; 2013 ZF2 Entity Audit</p>
                </footer>
            </div>

        </div>

    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
</body>
</html>
