<div class="row">
    <div class="span12">
        <h1>Edit Sample Data</h1>
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formLabel($form->get('name')); ?>
        <?php echo $this->formInput($form->get('name')); ?>
        <?php echo $this->formElementErrors($form->get('name')); ?>
        

        <?php echo $this->formLabel($form->get('tag')); ?>
        <?php echo $this->formInput($form->get('tag')); ?>
        <?php echo $this->formElementErrors($form->get('tag')); ?>
        
        
        
        
        <?php echo $this->formLabel($form->get('save')); ?>
        <?php echo $this->formInput($form->get('save')); ?>
        
        <?php
        echo $this->form()->closeTag($form);
        ?>
    </div>
</div>