<div class="row">
    <div class="span12">
        <h1>Edit Sample Data</h1>
        <?php echo $this->form()->openTag($form); ?>
        <?= $this->formRow($form->get('name')); ?>


        <?= $this->formRow($form->get('tag')); ?>

        <?= $this->formRow($form->get('save')); ?>

        <a class="confirm" href="/delete/<?= $type->getId(); ?>">
            delete
        </a>

        <?php
        echo $this->form()->closeTag($form);
        ?>
    </div>
</div>

<script>

$(function() {
    $('.confirm').on('click', function(event) {
        return confirm('Are you sure?');
    });
});

</script>

